import {Weapon} from "./weapon.model";

export const weaponList: Weapon[] = [
  {
    id: 1,
    weaponName: 'Single Shot',
    range: 50,
    strength: 10,
    weight: 30,
    explosionAppearance: '/assets/images/weapon/single_shot.png',
    spreadSpeed: 50,
    price: 50,
  },
  {
    id: 2,
    weaponName: 'Big Shot',
    range: 70,
    strength: 20,
    weight: 50,
    explosionAppearance: '/assets/images/weapon/big_shot.png',
    spreadSpeed: 70,
    price: 300,
  },
  {
    id: 3,
    weaponName: 'Three Shot',
    range: 50,
    strength: 10,
    weight: 30,
    explosionAppearance: '/assets/images/weapon/triple_shot.png',
    spreadSpeed: 50,
    price: 50,
    bounceNumber: 3,
    bounceDistance: 40,
  },
  {
    id: 4,
    weaponName: 'Five Shot',
    range: 50,
    strength: 10,
    weight: 30,
    explosionAppearance: '/assets/images/weapon/triple_shot.png',
    spreadSpeed: 50,
    price: 50,
    bounceNumber: 5,
    bounceDistance: 40,
  },
  {
    id: 5,
    weaponName: 'Blast',
    range: 50,
    strength: 35,
    weight: 20,
    explosionAppearance: '/assets/images/weapon/blast.png',
    spreadSpeed: 50,
    price: 3000,
  },
  {
    id: 6,
    weaponName: 'Mega Blast',
    range: 80,
    strength: 50,
    weight: 30,
    explosionAppearance: '/assets/images/weapon/mega-blast.png',
    spreadSpeed: 50,
    price: 7000,
  },
  {
    id: 7,
    weaponName: 'Mega Nuke',
    range: 100,
    strength: 100,
    weight: 100,
    explosionAppearance: '/assets/images/weapon/mega-nuke.png',
    spreadSpeed: 100,
    price: 30000,
  },
  {
    id: 8,
    weaponName: 'Nuke',
    range: 30,
    strength: 80,
    weight: 70,
    explosionAppearance: '/assets/images/weapon/nuke.png',
    spreadSpeed: 100,
    price: 18000,
  }
];
